language: go
go:
  - "1.10.x"

before_install:
  - go get
  - go get github.com/mattn/goveralls

script: "go test -v ./... -coverprofile=coverage.out -covermode=atomic -bench=./..."

after_success:
  - "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN"
